### ISSUE TITLE
groupPosition 

### ISSUE THREAD

**Issue by xucoolmeng** [msdx/group-recycler-adapter#4]
你好  我使用LRcyclerView https://github.com/jdsjlzx/LRecyclerView  只有一组数据  5个child  点击最后一个child 下标不对 groupPosition 变成了1

**Comment by msdx** [comment]
LRecyclerView 的原因。它将你所设置的 adapter 包装到它的一个 adapter 中。由于它的 adapter 带了头部，因此导致结果不正确。你在设置事件时，拿到了 adapterPosition 后应该再减去它的头部的 header 数。
具体可参考它的源码：https://github.com/jdsjlzx/LRecyclerView/blob/master/LRecyclerview_library/src/main/java/com/github/jdsjlzx/recyclerview/LRecyclerViewAdapter.java
